_BASE_: [
  '../datasets/EFID2023_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

architecture: DETR
weights: output/rtdetr_r50vd_6x_oad_kpts/model_final
find_unused_parameters: True
log_iter: 200
epoch: 75
add_rad: True
add_kpts: True

DETR:
  transformer: RTDETRTransformer_oad_kpts
  detr_head: DINOHEAD_oad_kpts
  post_process: DETRPostProcess_oad_kpts

RTDETRTransformer_oad_kpts:
  num_queries: 300
  position_embed_type: sine
  feat_strides: [8, 16, 32]
  num_levels: 3
  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.0
  activation: relu
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  learnt_init_query: False

DINOHEAD_oad_kpts:
  loss:
    name: DINOLoss_oad_kpts
    loss_coeff: {class: 1, bbox: 5, giou: 2, rad: 1}
    aux_loss: True
    use_vfl: True
    matcher:
      name: HungarianMatcher_oad
      matcher_coeff: {class: 2, bbox: 5, giou: 2, rad: 1}