_BASE_: [
  '../datasets/EFID2023_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: output/rtdetr_r50vd_6x_EFID2023/model_final
find_unused_parameters: True
log_iter: 200

DETR:
  detr_head: DINOoadHEAD
