metric: COCO
num_classes: 2   # class와 pose를 곱한 값

TrainDataset:
  name: OADDataSet
  image_dir: train/image
  anno_path: train/json/annotation.json
  dataset_dir: /DL_data_super_ssd/EFID2023/new_hallway
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd','gt_keypoint','gt_rad']

EvalDataset:
  name: OADDataSet
  image_dir: val/image
  anno_path: val/json/annotation.json
  dataset_dir: /DL_data_super_ssd/EFID2023/new_hallway
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: val/json/annotation.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /DL_data_super_ssd/EFID2023/new_hallway # if set, anno_path will be 'dataset_dir/anno_path'
